#
# HyprFlux ISO — pacman.conf for mkarchiso build
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# =============================================================================
# Official Repositories
# =============================================================================

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# =============================================================================
# HyprFlux Custom Local Repository (pre-built AUR packages)
# =============================================================================

[hyprflux]
SigLevel = Optional TrustAll
Server = file:///home/ahmad/Documents/Projects/Hyprflux-ISO/aur/repo
